# Generated by Django 5.1 on 2024-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0005_event_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='related_activities', to='OurEventApp.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='OurEventApp.activity'),
        ),
    ]
