# Generated by Django 5.1 on 2024-10-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0008_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='OurEventApp.event'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
