# Generated by Django 5.1 on 2024-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0009_media_event_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
