# Generated by Django 5.1 on 2024-10-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0010_event_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='OurEventApp.event')),
            ],
        ),
    ]
