# Generated by Django 5.1 on 2024-10-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0012_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
