# Generated by Django 5.1 on 2024-10-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0013_remove_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
    ]
