# Generated by Django 5.1 on 2024-10-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0014_remove_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
