# Generated by Django 5.1 on 2024-11-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0015_alter_media_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
