# Generated by Django 5.1 on 2024-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OurEventApp', '0017_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.AddField(
            model_name='partner',
            name='link_page',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
